spring.application.name=BookApplication
ron.inetpsa.Developer=Ronish
ron.inetpsa.Comment=This is a Book Application, developed by ${ron.inetpsa.Developer}

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=ronish


spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

management.endpoints.web.exposure.include=*


