spring.application.name=SpringBatchDemo

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=ronish

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

#disabled job run at startup
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false